# scrutinizer-ci.com configuration
imports:
  - php
filter:
  excluded_paths:
    - build/
    - tmp/
    - vendor/
    - ci/doctum-config.php
checks:
  php: true
tools:
  external_code_coverage:
    runs: 4 # php 7.x versions * 2
    timeout: 480 # 8 min
build:
  nodes:
    analysis:
      environment:
        php:
          version: 8.2
          pecl_extensions:
            - dbase
      dependencies:
        before:
          - composer install
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
