language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  exclude:
    - php: "hhvm"
      env: DBASE=yes

env:
  matrix:
    - DBASE=yes
    - DBASE=no

install:
  - if [ "$DBASE" = "yes" ] ; then ./ci/install-dbase ; fi
  - composer install

script: 
  - phpunit --configuration phpunit.xml
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
