language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
      env: DBASE=yes
    - php: 7.2
      env: DBASE=yes
    - php: 7.3
      env: DBASE=yes
    - php: 7.1
      env: DOCS=yes

install:
  - if [ "$DBASE" = "yes" ] ; then ./ci/install-dbase ; fi
  - composer install

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..
  - if [ "$DOCS" = "yes" ] ; then ./vendor/bin/sami.php --no-interaction update ./ci/sami-config.php ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
