language: php

dist: trusty

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "hhvm-3.12"
  - "hhvm-3.18"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "5.6"
      env: DBASE=yes
    - php: "7.0"
      env: DBASE=yes
    - php: "7.1"
      env: DBASE=yes
    - php: "7.2"
      env: DBASE=yes
    - php: "7.1"
      env: DOCS=yes

install:
  - if [ "$DBASE" = "yes" ] ; then pecl install dbase-beta ; fi
  - composer install

script: 
  - ./vendor/bin/phpunit --configuration phpunit.xml
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..
  - if [ "$DOCS" = "yes" ] ; then ./vendor/bin/apigen generate --destination doc --source src/ ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
