language: php

dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DBASE=no
  - DBASE=yes

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
      name: "Documentation"
      script: vendor/bin/sami.php --no-interaction update ./ci/sami-config.php
    - php: 7.1
      name: "Coding standard"
      script: vendor/bin/phpcs
    - php: nightly
      env: DBASE=no
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: nightly
      env: DBASE=yes
      install:
        - composer install --no-interaction --ignore-platform-reqs

before_install:
  - |
    if [[ "$DBASE" == "yes" ]]; then
        pecl channel-update pecl.php.net
        pecl install dbase
    fi

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
