language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - pip install --user codecov

install:
  - git clone --depth 1 git://github.com/mote0230/dbase-pecl-php7.git php7-dbase
  - cd php7-dbase/
  - phpize
  - ./configure
  - make
  - make install
  - cd ..
  - composer install

script: 
  - phpunit --configuration phpunit.xml

after_success:
  - codecov

cache:
  directories:
    - $HOME/.composer/cache
