language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"
env:
  matrix:
    - DBASE=yes
    - DBASE=no
matrix:
  exclude:
    - php: "hhvm"
      env: DBASE=yes

before_install:
  - pip install --user codecov

install:
  - if [ "$DBASE" = "yes" ] ; then ./ci/install-dbase ; fi
  - composer install

script: 
  - phpunit --configuration phpunit.xml
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..

after_success:
  - codecov

cache:
  directories:
    - $HOME/.composer/cache
