language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - pip install --user codecov

install:
  - ./ci/install-dbase
  - composer install

script: 
  - phpunit --configuration phpunit.xml
  - php examples/create_shapefile.php
  - php examples/read_point.php
  - php examples/read_polygon.php

after_success:
  - codecov

cache:
  directories:
    - $HOME/.composer/cache
