language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
- composer install
- pecl install dbase
- echo 'extension = dbase.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: 
- phpunit --configuration phpunit.xml
